apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-secrets-controller-manager
  namespace: external-secrets-system
spec:
  template:
    spec:
      containers:
      - name: manager
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: aws-credentials
