name: CRDs

on:
  push:
    branches:
      - main
      - release-*
    paths:
      - 'apis/**'
  pull_request:
    paths:
      - 'apis/**'
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  crd-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Generate crds for testing
        run: make crds.generate.tests

      - name: Run crd tests
        run: make test.crds
