name: Helm

on:
  push:
    branches:
      - main
      - release-*
    paths:
      - 'deploy/charts/**'
  pull_request:
    paths:
      - 'deploy/charts/**'
  workflow_dispatch: {}

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Generate chart
        run: |
          make helm.generate

      - name: Set up Helm
        uses: azure/setup-helm@v1.1
        with:
          version: v3.4.2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.1.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config=.github/ci/ct.yaml)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        run: ct lint --config=.github/ci/ct.yaml

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set up Helm
        uses: azure/setup-helm@v1.1
        with:
          version: v3.4.2

      - name: Generate chart
        run: |
          make helm.generate

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.2.1
        if: github.ref == 'refs/heads/main'
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_RELEASE_NAME_TEMPLATE: "helm-chart-{{ .Version }}"
        with:
          charts_dir: deploy/charts
          charts_repo_url: https://charts.external-secrets.io

  olm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1.1
        with:
          version: v3.4.2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - uses: shivanshs9/setup-k8s-operator-sdk@v1
        with:
          version: "^1.15.0"

      - name: Login to Docker
        uses: docker/login-action@v1
        if: env.GHCR_USERNAME != ''
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: get helm version
        id: helmVersion
        uses: mikefarah/yq@master
        with:
          cmd: yq e .version deploy/charts/external-secrets/Chart.yaml

      - name: Generate olm bundle & push image
        if: github.ref == 'refs/heads/main'
        run: |
          make olm.bundle VERSION=${{ steps.helmVersion.outputs.result }}
          make olm.image.build VERSION=${{ steps.helmVersion.outputs.result }}
          make olm.image.push VERSION=${{ steps.helmVersion.outputs.result }}
